### ISSUE TITLE
Small issue with Setup SSH in linux and connect to it from Windows

### ISSUE THREAD

**Issue by MikaelSpinnangr** [Sonderwoods/MantaRay#105]
when following the tutorial https://www.illuminiastudios.com/dev-diaries/ssh-on-windows-subsystem-for-linux/ 

I am stuck at Edit the sshd_config part 

I can access the swap file and change the things like it is suggested but I can't save and exit. When pressing ctrl-x i get a menu and it does not save and exits. see picture 
![how to exit](https://user-images.githubusercontent.com/89906534/189483408-4242529c-bb56-4828-95fc-d8cb86178f4e.png)

I am quite new to Linux and PowerShell so this could be very easy to solve maybe  

what am I missing, any ideas?

**Comment by Sonderwoods** [comment]
Ctrl+x then type Y and hit enter. Works in nano. Unsure with Wim.

I usually edit with nano and not vim. Use

sudo nano ~/.bashrc

lør. 10. sep. 2022 14.31 skrev Mikael Spinnangr ***@***.***>:

**Comment by MikaelSpinnangr** [comment]
fantastic that did it 

![Wohooo ](https://user-images.githubusercontent.com/89906534/189500935-47bb0261-9ad0-4e9c-8027-c152f38a4583.png)

and I have echo now :) 
![Echoo](https://user-images.githubusercontent.com/89906534/189500942-ce6c5e66-bb2b-466e-95b6-aa2658663aec.png)
